host: 0.0.0.0
port: 80
balancing: round-robin

servers:
  - scheme: http
    host: 192.168.33.11
    port: 1111

  - scheme: http
    host: 192.168.33.11
    port: 2222

  - scheme: http
    host: 192.168.33.11
    port: 3333
