host: 0.0.0.0
scheme: http
port: 8080
balancing: round-robin
servers:
  - scheme: http
    host: 0.0.0.0
    port: 1234
  - scheme: http
    host: 0.0.0.0
    port: 5678
  - scheme: http
    host: 0.0.0.0
    port: 3333
